import { Transaction, Task, User, Loan, LoanPayment } from '@/types';

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  monthlySalary: 24800000,
};

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    userId: '1',
    type: 'income',
    amount: 24800000,
    category: 'salary',
    description: 'Monthly salary',
    date: new Date('2025-08-01'),
  },
  {
    id: '2',
    userId: '1',
    type: 'expense',
    amount: 2000000,
    category: 'food',
    description: 'Groceries and meals',
    date: new Date('2025-08-02'),
  },
  {
    id: '3',
    userId: '1',
    type: 'expense',
    amount: 400000,
    category: 'coffee',
    description: 'Daily coffee and cafes',
    date: new Date('2025-08-03'),
  },
  {
    id: '4',
    userId: '1',
    type: 'expense',
    amount: 500000,
    category: 'oil',
    description: 'Gas for car',
    date: new Date('2025-08-04'),
  },
  {
    id: '5',
    userId: '1',
    type: 'expense',
    amount: 1500000,
    category: 'family',
    description: 'Family expenses',
    date: new Date('2025-08-05'),
  },
  {
    id: '6',
    userId: '1',
    type: 'expense',
    amount: 800000,
    category: 'debt',
    description: 'Credit card payment',
    date: new Date('2025-08-06'),
  },
  {
    id: '7',
    userId: '1',
    type: 'expense',
    amount: 600000,
    category: 'shopping',
    description: 'Clothes and essentials',
    date: new Date('2025-08-06'),
  },
  {
    id: '8',
    userId: '1',
    type: 'expense',
    amount: 300000,
    category: 'entertain',
    description: 'Movies and games',
    date: new Date('2025-08-06'),
  },
  {
    id: '9',
    userId: '1',
    type: 'income',
    amount: 2000000,
    category: 'freelance',
    description: 'Side project payment',
    date: new Date('2025-08-01'),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    userId: '1',
    title: 'Complete project proposal',
    description: 'Finish the Q1 project proposal for the client',
    completed: false,
    priority: 'high',
    type: 'daily',
    dueDate: new Date('2025-08-07'),
    createdAt: new Date('2025-08-05'),
    updatedAt: new Date('2025-08-05'),
  },
  {
    id: '2',
    userId: '1',
    title: 'Review budget',
    description: 'Monthly budget review and planning',
    completed: true,
    priority: 'medium',
    type: 'monthly',
    dueDate: new Date('2025-08-31'),
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2025-08-06'),
  },
  {
    id: '3',
    userId: '1',
    title: 'Update portfolio website',
    description: 'Add recent projects to portfolio',
    completed: false,
    priority: 'low',
    type: 'monthly',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2025-08-01'),
  },
  {
    id: '4',
    userId: '1',
    title: 'Schedule dentist appointment',
    description: 'Book routine dental checkup',
    completed: false,
    priority: 'medium',
    type: 'daily',
    dueDate: new Date('2025-08-08'),
    createdAt: new Date('2025-08-06'),
    updatedAt: new Date('2025-08-06'),
  },
  {
    id: '5',
    userId: '1',
    title: 'Plan vacation',
    description: 'Research and book summer vacation',
    completed: false,
    priority: 'low',
    type: 'monthly',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-01'),
    updatedAt: new Date('2025-08-01'),
  },
];

export const categories = {
  income: ['Salary', 'Freelance', 'Investment', 'Business', 'Bonus', 'Other'],
  expense: ['Food', 'Coffee', 'Oil', 'Family', 'Debt', 'Shopping', 'Entertainment'],
};

// Category icons and colors for better UX
export const categoryConfig = {
  // Income categories
  'Salary': { icon: '💰', color: 'emerald' },
  'Freelance': { icon: '💻', color: 'blue' },
  'Investment': { icon: '📈', color: 'green' },
  'Business': { icon: '🏢', color: 'purple' },
  'Bonus': { icon: '🎁', color: 'orange' },
  'Other': { icon: '💸', color: 'gray' },
  
  // Expense categories
  'Food': { icon: '🍽️', color: 'red' },
  'Coffee': { icon: '☕', color: 'amber' },
  'Oil': { icon: '⛽', color: 'yellow' },
  'Family': { icon: '👨‍👩‍👧‍👦', color: 'pink' },
  'Debt': { icon: '💳', color: 'rose' },
  'Shopping': { icon: '🛍️', color: 'indigo' },
  'Entertainment': { icon: '🎬', color: 'violet' },
};

export const mockLoans: Loan[] = [
  {
    id: '1',
    userId: '1',
    title: 'Car Loan',
    totalAmount: 25000,
    amountPaid: 5000,
    remainingAmount: 20000,
    monthlyPayment: 450,
    interestRate: 3.5,
    startDate: new Date('2024-01-15'),
    targetPayoffDate: new Date('2029-01-15'),
    category: 'auto',
    description: 'Honda Civic 2024 financing',
    isActive: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2025-08-01'),
  },
  {
    id: '2',
    userId: '1',
    title: 'Student Loan',
    totalAmount: 45000,
    amountPaid: 12000,
    remainingAmount: 33000,
    monthlyPayment: 320,
    interestRate: 4.2,
    startDate: new Date('2020-09-01'),
    targetPayoffDate: new Date('2030-09-01'),
    category: 'student',
    description: 'Master\'s degree tuition loan',
    isActive: true,
    createdAt: new Date('2020-09-01'),
    updatedAt: new Date('2025-08-01'),
  },
  {
    id: '3',
    userId: '1',
    title: 'Personal Loan',
    totalAmount: 10000,
    amountPaid: 8500,
    remainingAmount: 1500,
    monthlyPayment: 300,
    interestRate: 6.8,
    startDate: new Date('2023-06-01'),
    targetPayoffDate: new Date('2026-06-01'),
    category: 'personal',
    description: 'Home improvement loan',
    isActive: true,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2025-08-01'),
  },
];

export const mockLoanPayments: LoanPayment[] = [
  {
    id: '1',
    loanId: '1',
    amount: 450,
    paymentDate: new Date('2025-07-15'),
    description: 'Monthly payment',
  },
  {
    id: '2',
    loanId: '1',
    amount: 450,
    paymentDate: new Date('2025-06-15'),
    description: 'Monthly payment',
  },
  {
    id: '3',
    loanId: '2',
    amount: 320,
    paymentDate: new Date('2025-07-01'),
    description: 'Monthly payment',
  },
  {
    id: '4',
    loanId: '3',
    amount: 300,
    paymentDate: new Date('2025-07-10'),
    description: 'Monthly payment',
  },
  {
    id: '5',
    loanId: '3',
    amount: 500,
    paymentDate: new Date('2025-06-10'),
    description: 'Extra payment to reduce principal',
  },
];
